### ISSUE TITLE
No GME share price

### ISSUE THREAD

**Issue by Rohrreiniger** [makinori/gme-to-the-moon#2]
Since a few days no (fake) price is displayed on the rocket in the browser. Thanks!

**Comment by makifoxgirl** [comment]
That's so strange. Do you see anything at all next to the rocket? For example, 3 dots ("...") on a gray background? Or is there no badge whatsoever.

**Comment by makifoxgirl** [comment]
I think I've figured out the issue. It happens when you restart Chrome. It's related to the manifest v3. Looking into fixing it now

**Comment by makinori** [comment]
I've updated the extension. It'll be live after Google or Mozilla reviewed it
